import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

type PackageJson = {
  name: string;
  description?: string;
  homepage?: string;
  llms?: string;
  llmsFull?: string;
  skills?: string;
  agents?: { skills: Array<{ name: string; path: string }> };
  repository?: { url?: string; directory?: string };
};

const packageDir = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const packageJson = JSON.parse(
  readFileSync(path.join(packageDir, "package.json"), "utf8"),
) as PackageJson;

function parseGitHubRepo(url: string | undefined) {
  const match = url?.match(/github\.com[/:]([^/]+)\/([^/.]+)/);
  return match ? { owner: match[1], name: match[2].replace(/\.git$/, "") } : null;
}

function getDocsSiteBase(packageDirName: string, repositoryUrl: string | undefined) {
  const repo = parseGitHubRepo(repositoryUrl);
  return `https://${repo!.owner}.github.io/${repo!.name}/${packageDirName}`;
}

const packageSlug = path.basename(packageDir);
const npmName = packageJson.name;
const npmSlug = npmName.replace("/", "%2f");
const repo = parseGitHubRepo(packageJson.repository?.url);
const siteBase = getDocsSiteBase(packageSlug, packageJson.repository?.url);
const docsUrl = `${siteBase}/docs`;
const repoUrl = packageJson.repository?.url?.replace(/^git\+/, "").replace(/\.git$/, "");
const repoTreeUrl =
  repoUrl && packageJson.repository?.directory
    ? `${repoUrl}/tree/main/${packageJson.repository.directory}`
    : repoUrl;
const skillGitUrl =
  repoUrl && packageJson.repository?.directory
    ? `${repoUrl}/tree/main/${packageJson.repository.directory}/skills/${packageSlug}`
    : undefined;
const ciWorkflow = "on-push-main-seodit.yml";
const ciBadgeUrl = `https://img.shields.io/github/actions/workflow/status/${repo!.owner}/${repo!.name}/${ciWorkflow}?branch=main&label=main`;
const ciLinkUrl = `https://github.com/${repo!.owner}/${repo!.name}/actions?query=branch%3Amain`;

const badges = [
  `[![npm version](https://img.shields.io/npm/v/${npmSlug})](https://www.npmjs.com/package/${npmSlug})`,
  `[![npm downloads](https://img.shields.io/npm/dm/${npmSlug})](https://www.npmjs.com/package/${npmSlug})`,
  `[![main](${ciBadgeUrl})](${ciLinkUrl})`,
  `[![skills.sh](https://skills.sh/b/${repo!.owner}/${repo!.name})](https://skills.sh/${repo!.owner}/${repo!.name})`,
].join("\n");

const readme = `<!-- Generated by scripts/readme-gen.ts -->

# ${npmName}

${badges}

${packageJson.description}

## Install

\`\`\`bash
npm install ${npmName} @playwright/test
\`\`\`

Install from npm in the application where your Playwright tests run. The package extends your existing \`@playwright/test\` expect instance instead of exporting its own test runner.

## Agent skill (optional)

For Cursor and other coding agents. [Agent skill docs](${docsUrl}/agent-skill).

**Option A — \`npx skills\` (git)**

\`\`\`bash
npx skills add ${skillGitUrl ?? `${repo!.owner}/${repo!.name}`} -a cursor -y
\`\`\`

Use this option when you want to install the skill directly from its Git source.

**Option B — \`skills-npm\` (version-locked)**

\`\`\`bash
npm i -D skills-npm
npx skills-npm setup
npm install ${npmName}
\`\`\`

## Documentation

- [Docs](${docsUrl})
- [llms.txt](${siteBase}/llms.txt)
- [llms-full.txt](${siteBase}/llms-full.txt)
${repoTreeUrl ? `- [Source](${repoTreeUrl})` : ""}
- [npm](https://www.npmjs.com/package/${npmSlug})
`;

writeFileSync(path.join(packageDir, "README.md"), readme);

const skillDir = path.join(packageDir, "skills", packageSlug);
mkdirSync(skillDir, { recursive: true });

const skill = `---
name: ${packageSlug}
description: Integrate ${npmName} Playwright SEO assertions in Next.js apps. Use when adding seodit, extendSeoditExpect, *.seodit.spec.ts, canonical, hreflang, meta title, or JSON-LD checks.
---

<!-- Generated by scripts/readme-gen.ts -->

# ${packageSlug}

${packageJson.description}

## When to use

- Integrating ${npmName} into a Next.js + Playwright app
- Adding or updating \`*.seodit.spec.ts\` route SEO specs
- Checking canonical URLs, hreflang alternates, meta title, or JSON-LD

## Instructions

1. Install: \`npm install ${npmName} @playwright/test\`.
2. Read docs — from the installed package \`package.json\` (\`llms\`, \`llmsFull\`, \`homepage\`) or:
   - [llms.txt](${siteBase}/llms.txt)
   - [llms-full.txt](${siteBase}/llms-full.txt)
   - [Getting started](${docsUrl}/getting-started)
   - [Playwright guide](${docsUrl}/playwright)
   - [Next.js adapter](${docsUrl}/next)
   - [API reference](${docsUrl}/api)
3. For Next.js + next-intl apps, add \`seodit.next.config.ts\` with \`routing\` only and use \`createSeoditPageRoutes(config, import.meta.url)\` in colocated \`page.seodit.spec.ts\` files.
4. Follow the Playwright guide for project layout, \`extendSeoditExpect\`, and matchers.

## Key rules

- Do not import \`test\` or \`expect\` from \`${npmName}\` — use local \`@playwright/test\`.
- Prefer granular matchers over one-shot audits.
`;

writeFileSync(path.join(skillDir, "SKILL.md"), skill);

packageJson.homepage = docsUrl;
packageJson.llms = `${siteBase}/llms.txt`;
packageJson.llmsFull = `${siteBase}/llms-full.txt`;
packageJson.skills = skillGitUrl;
packageJson.agents = {
  skills: [{ name: packageSlug, path: `./skills/${packageSlug}` }],
};
writeFileSync(
  path.join(packageDir, "package.json"),
  `${JSON.stringify(packageJson, null, 2)}\n`,
);
