import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

type PackageJson = {
  name: string;
  description?: string;
  repository?: { url?: string; directory?: string };
};

const packageDir = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const packageJson = JSON.parse(
  readFileSync(path.join(packageDir, "package.json"), "utf8"),
) as PackageJson;

function parseGitHubRepo(url: string | undefined) {
  const match = url?.match(/github\.com[/:]([^/]+)\/([^/.]+)/);
  return match ? { owner: match[1], name: match[2].replace(/\.git$/, "") } : null;
}

function getDocsSiteBase(packageDirName: string, repositoryUrl: string | undefined) {
  const repo = parseGitHubRepo(repositoryUrl);
  return `https://${repo!.owner}.github.io/${repo!.name}/${packageDirName}`;
}

const packageSlug = path.basename(packageDir);
const npmName = packageJson.name;
const npmSlug = npmName.replace("/", "%2f");
const repo = parseGitHubRepo(packageJson.repository?.url);
const siteBase = getDocsSiteBase(packageSlug, packageJson.repository?.url);
const docsUrl = `${siteBase}/docs`;
const repoUrl = packageJson.repository?.url?.replace(/^git\+/, "").replace(/\.git$/, "");
const repoTreeUrl =
  repoUrl && packageJson.repository?.directory
    ? `${repoUrl}/tree/main/${packageJson.repository.directory}`
    : repoUrl;
const ciWorkflow = "publish-seodit.yml";
const ciBadgeUrl = `https://github.com/${repo!.owner}/${repo!.name}/actions/workflows/${ciWorkflow}/badge.svg?branch=main`;
const ciLinkUrl = `https://github.com/${repo!.owner}/${repo!.name}/actions/workflows/${ciWorkflow}?query=branch%3Amain`;

const badges = [
  `[![npm version](https://img.shields.io/npm/v/${npmSlug})](https://www.npmjs.com/package/${npmSlug})`,
  `[![npm downloads](https://img.shields.io/npm/dm/${npmSlug})](https://www.npmjs.com/package/${npmSlug})`,
  `[![CI](${ciBadgeUrl})](${ciLinkUrl})`,
].join("\n");

const readme = `<!-- Generated by scripts/readme-gen.ts -->

# ${npmName}

${badges}

${packageJson.description}

## Install

\`\`\`bash
npm install ${npmName}
\`\`\`

## Documentation

- [Docs](${docsUrl})
- [llms.txt](${siteBase}/llms.txt)
- [llms-full.txt](${siteBase}/llms-full.txt)
${repoTreeUrl ? `- [Source](${repoTreeUrl})` : ""}
- [npm](https://www.npmjs.com/package/${npmSlug})
`;

writeFileSync(path.join(packageDir, "README.md"), readme);
