name: on-push-main

on:
  workflow_call:
    inputs:
      skip-audit:
        type: boolean
        default: false
        description: Skip npm audit job

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-node-npm-ci
      - run: npm run lint

  check-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-node-npm-ci
      - run: npm run check-types

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-node-npm-ci
      - run: npm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-node-npm-ci
      - run: npm run test

  audit:
    if: ${{ !inputs.skip-audit }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-node-npm-ci
      - run: npm audit --audit-level=critical
